version: '3'
services:
  mongodb:
    container_name: mongodb-container
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./docker-volumes/mongodb:/data/db
    ports:
      - 27017:27017

  postgres:
    container_name: postgres-container
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3.10-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./docker-volumes/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  webapi:
    container_name: webapi-container
    image: node:16.15
    working_dir: /usr/src/webapi-nodejs
    command: bash -c "npm ci --omit=dev && npm run debug"
    env_file: .env
    environment:
      - MONGODB_HOST=mongodb
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./dist:/usr/src/webapi-nodejs/dist
      - ./.npmrc:/usr/src/webapi-nodejs/.npmrc
      - ./package.json:/usr/src/webapi-nodejs/package.json
      - ./package-lock.json:/usr/src/webapi-nodejs/package-lock.json
      - ./docker-volumes/npm-cache:/root/.npm
    ports:
      - ${PORT}:${PORT}
      - 9222:9222
    links:
      - ${PERSISTENCE}
      - rabbitmq
    depends_on:
      - ${PERSISTENCE}
      - rabbitmq
