version: '3'
services:
  postgres:
    container_name: postgres-container
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongodb:
    container_name: mongodb-container
    image: mongo:4.4
    restart: always
    volumes:
      - ./data-mongodb:/data/db
    ports:
      - 27017:27017

  webapi:
    container_name: webapi-container
    image: node:14
    working_dir: /usr/src/webapi-nodejs
    restart: always
    command: bash -c "npm ci --only=prod && npm run debug"
    env_file: .env
    volumes:
      - ./dist:/usr/src/webapi-nodejs/dist
      - ./package.json:/usr/src/webapi-nodejs/package.json
      - ./package-lock.json:/usr/src/webapi-nodejs/package-lock.json
    ports:
      - '${PORT}:${PORT}'
      - 9222:9222
    links:
      - postgres
      - mongodb

  start_dependencies:
    container_name: wait-for-dependencies
    image: dadarek/wait-for-dependencies
    command: postgres:5432 mongodb:27017 webapi:3000
    depends_on:
      - postgres
      - mongodb
      - webapi
