version: '3'
services:
  postgres:
    container_name: postgres-container
    image: postgres:14.1
    environment:
      - POSTGRES_DB=${DB_POSTGRES_DATABASE}
      - POSTGRES_USER=${DB_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
      - ./docker-postgres.sh:/docker-entrypoint-initdb.d/docker-postgres.sh
    ports:
      - 5432:5432

  webapi:
    container_name: webapi-container
    image: node:16.15
    working_dir: /usr/src/webapi-nodejs
    command: bash -c "npm ci --production --legacy-peer-deps && npm run debug"
    env_file: .env
    environment:
      - DB_POSTGRES_HOST=postgres
    volumes:
      - ./dist:/usr/src/webapi-nodejs/dist
      - ./ormconfig.js:/usr/src/webapi-nodejs/ormconfig.js
      - ./package.json:/usr/src/webapi-nodejs/package.json
      - ./package-lock.json:/usr/src/webapi-nodejs/package-lock.json
    ports:
      - ${PORT}:${PORT}
      - 9222:9222
    links:
      - postgres

  start_dependencies:
    container_name: wait-for-dependencies
    image: dadarek/wait-for-dependencies
    command: postgres:5432 webapi:3000
    depends_on:
      - postgres
      - webapi
