version: '3'
services:
  mongodb:
    container_name: mongodb-container
    image: mongo:4.4
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017

  webapi:
    container_name: webapi-container
    image: node:14
    working_dir: /usr/src/webapi-nodejs
    restart: always
    command: bash -c "npm ci --only=prod && npm run debug"
    env_file: .env
    volumes:
      - ./dist:/usr/src/webapi-nodejs/dist
      - ./package.json:/usr/src/webapi-nodejs/package.json
      - ./package-lock.json:/usr/src/webapi-nodejs/package-lock.json
    ports:
      - '${PORT}:${PORT}'
      - 9222:9222
    links:
      - mongodb

  start_dependencies:
    container_name: wait-for-dependencies
    image: dadarek/wait-for-dependencies
    command: mongodb:27017 webapi:3000
    depends_on:
      - mongodb
      - webapi
