@startuml Base
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
  
  ' Colors
  !$color_fg = "#4"

  ' Theme
  !include dark.puml

  ' Logos
  !define  LOGOS https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/logos
  !include LOGOS/nodejs.puml
  !include LOGOS/rabbitmq.puml
  !include LOGOS/mongodb.puml

  ' Definitions
  SHOW_PERSON_OUTLINE()

  ' Tags
  AddRelTag("async", $color_fg, $color_fg, DashedLine())
@enduml
