@startuml Container Diagram | Sign up
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
  !define FA https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/tupadr3/font-awesome-5
  !define LOGOS https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/logos
  !include LOGOS/postgresql.puml
  !include LOGOS/nodejs.puml

  AddRelTag("async", $lineStyle = DashedLine())

  SHOW_PERSON_PORTRAIT()

  Person(user, "User")
  System_Ext(front, "Webapp", "Frontend application")

  System_Boundary(webapi, "webapi-nodejs") {
    Container(back, "Backend", "Node.js", "Backend application", $sprite="nodejs")
    ContainerDb(persistence, "persistence", "postgres", "application persistence", $sprite="postgresql")
  }

  Rel(user, front, "1.1. Signs in", "https/json")
  Rel(front, back, "1.2. Signs in an user", "https/json")
  Rel(back, persistence, "1.3. Reads an user", "SQL/TCP", $tags="async" )

  SHOW_LEGEND()
@enduml
