@startuml System Context Diagram
  !include common/base.puml

  title System Context Diagram | Webapi-nodejs

  Person(user, "User", "User of the webapp system")
  System_Ext(front, "Webapp", "Client-side web application")
  System_Ext(emailSystem, "E-mail System", "External e-mail system")

  System(system, "Webapi-nodejs System", "Server-side web application")

  Rel(user,  front, "Uses")
  Rel(front, system, "Consumes")
  Rel(system, emailSystem, "Sends e-mails using", $tags="async")
@enduml
