@startuml Container Diagram
  !include common/base.puml

  title Container Diagram | Webapi-nodejs

  Person(user, "User", "User of the webapp system")
  System_Ext(front, "Webapp", "Client-side web application")
  System_Ext(emailSystem, "E-mail System", "External e-mail system")

  System(system, "Webapi-nodejs System", "Server-side web application")

  System_Boundary(system, "Webapi-nodejs System") {
    Container(back, "API Application", "Node.js", "Server-side web application", $sprite="nodejs")
    ContainerDb(persistence, "persistence", "mongodb", "Application persistence", $sprite="mongodb")
    ContainerQueue(userCreatedTopic, "userCreatedTopic", "rabbitmq", "userCreated topic", $sprite="rabbitmq")
    ContainerQueue(userCreatedQueue, "userCreatedQueue", "rabbitmq", "userCreated queue", $sprite="rabbitmq")
  }

  Rel(user, front, "Uses", "https/json")
  Rel(front, back, "Consumes", "https/json")
  Rel(back, persistence, "Reads from \nand wirtes to", "TCP/IP", $tags="async" )
  Rel(back, userCreatedTopic, "Emmits events to", "amqp", $tags="async")
  Rel(userCreatedQueue, userCreatedTopic, "Subscribes to", "amqp", $tags="async")
  Rel(back, userCreatedQueue, "Handles events from", "amqp", $tags="async")
  Rel(back, emailSystem, "Sends e-mails using", "smtp", $tags="async")
@enduml
