@startuml Container Diagram
  !include common/base.puml
  !define DIAGRAM Container Diagram | Webapi-nodejs
  !define CREATED 2023-06-04
  !define UPDATED 2023-08-27

  title DIAGRAM

  Person(user, "User", "User of the webapp system")
  System_Ext(webapp, "Webapp", "Client-side web application")
  System_Ext(emailSystem, "E-mail System", "External e-mail system")

  System_Boundary(system, "Webapi-nodejs System") {
    Container(webapi, "API Application", "Node.js", "Server-side web application", $sprite="nodejs")
    ContainerDb(persistence, "persistence", "mongodb", "Application persistence", $sprite="mongodb")
    ContainerQueue(userEventsTopic, "userEventsTopic", "rabbitmq", "User related events", $sprite="rabbitmq")
    ContainerQueue(userSetGroupQueue, "userSetGroupQueue", "rabbitmq", "To set default group to new users", $sprite="rabbitmq")
    ContainerQueue(userSendEmailConfirmationQueue, "userSendEmailConfirmationQueue", "rabbitmq", "To send e-mail confirmation to new users", $sprite="rabbitmq")
  }

  Rel(user, webapp, "Uses", "https/json")
  Rel(webapp, webapi, "Consumes", "https/json")
  Rel(webapi, persistence, "Reads from \nand wirtes to", "TCP/IP", $tags="async" )
  Rel(webapi, userEventsTopic, "Emmits events to", "amqp", $tags="async")
  Rel(webapi, userSetGroupQueue, "Handles events from", "amqp", $tags="async")
  Rel(webapi, userSendEmailConfirmationQueue, "Handles events from", "amqp", $tags="async")
  Rel(webapi, emailSystem, "Sends e-mails using", "smtp", $tags="async")
  Rel(userSetGroupQueue, userEventsTopic, "Subscribes to", "amqp", $tags="async")
  Rel(userSendEmailConfirmationQueue, userEventsTopic, "Subscribes to", "amqp", $tags="async")

  footer DIAGRAM (created at CREATED, updated at UPDATED)

  SHOW_LEGEND()
@enduml
